springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8095
  servlet:
    context-path: /
spring:
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  datasource:
    url: ${PERSISTENCE_URL:jdbc:mysql://localhost:3306/cohelum}
    username: ${PERSISTENCE_USER:devLocal}
    password: ${PERSISTENCE_PASSWORD:Dev2022$}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

