server:
  port: 8095
  servlet:
    context-path: /
spring:
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  datasource:
    url: ${PERSISTENCE_URL:jdbc:mysql://localhost:3306/cohelum}
    username: ${PERSISTENCE_USER:root}
    password: ${PERSISTENCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
